parameters:
#    application_home.example.class: Application\HomeBundle\Example

services:
#    application_home.example:
#        class: %application_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
